# Generated by Django 5.0 on 2024-01-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0007_alter_budget_month'),
    ]

    operations = [
        migrations.RenameField(
            model_name='budget',
            old_name='name',
            new_name='budget_entry_name',
        ),
        migrations.AlterField(
            model_name='budget',
            name='month',
            field=models.CharField(choices=[('Jan', 'January'), ('Feb', 'February'), ('Mar', 'March'), ('Apr', 'April'), ('May', 'May'), ('June', 'June'), ('July', 'July'), ('Aug', 'August'), ('Sep', 'September'), ('Oct', 'October'), ('Nov', 'November'), ('Dec', 'December')], default='Jan', max_length=20),
        ),
    ]
